[package]
name = "lc3-emulator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
crossterm = "0.29.0"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
tsify = "0.4.5"
wasm-bindgen = "0.2.100"
